POA.Web/Models/Title/EditTitleForm.cs
using StructureMap;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.WebPages.Html;
using POA.Domain;
using POA.Web.Filters;
using POA.Web.Infrastructure.Mapping;
using StructureMap.TypeRules;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Data.Entity;

namespace POA.Web.Models.Title
{
    public class EditTitleForm : IMapFrom<Domain.Title>
    {
        [HiddenInput]
        public int Title_ID { get; set; }

         [Required]
        public string Title_Name { get; set; }

        [DataType(DataType.MultilineText)]
        public string Title_Description { get; set; }
         
        
        //var dbContext = Context.GetContainer().GetInstance<POADBEntities>();
       
       // [DataType("Country")]
       // public Domain.Country Country { get; set; }
        //public System.Web.Mvc.SelectListItem[] AvailableCountries { get; set; }
            
        
    }
}

POA.Web/Models/Title/NewTitleForm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.WebPages.Html;
using POA.Web.Filters;
using POA.Web.Infrastructure.Mapping;

namespace POA.Web.Models.Title
{
    public class NewTitleForm : IMapFrom<Domain.Title>
    {
        [HiddenInput]
        public int Title_ID { get; set; }
        [Required]
        public string Title_Name { get; set; }
        [DataType(DataType.MultilineText)]
        public string Title_Description { get; set; }

        
       // public Domain.Country Country { get; set; }
       // public System.Web.Mvc.SelectListItem[] AvailableCountries { get; set; }

        
    }
}

POA.Web/Models/Title/TitleDetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using POA.Web.Infrastructure.Mapping;

namespace POA.Web.Models.Title
{
    public class TitleDetailsViewModel : IMapFrom<Domain.Title>
    {
        public int Title_ID { get; set; }
        public string Title_Name { get; set; }
        public string Title_Description { get; set; }
    }
}

POA.Web/Models/Title/TitleSummaryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using POA.Web.Infrastructure.Mapping;
using POA.Domain;

namespace POA.Web.Models.Title
{
    public class TitleSummaryViewModel : IMapFrom<POA.Domain.Title>
    {
        public int Title_ID { get; set; }
        public string Title_Name { get; set; }
        public string Title_Description { get; set; }
        
    }
}

POA.Web/Controllers/TitleController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using POA.Domain;
using POA.Web.Filters;
using POA.Web.Models;
using POA.Web.Models.Title;
using Microsoft.Web.Mvc;
using POA.Web.Infrastructure.Alerts;
using AutoMapper.QueryableExtensions;


namespace POA.Web.Controllers
{
    public class TitleController : BaseController
    {

        private readonly POADBEntities _context;
        private Title _title { get; set; }

        public TitleController(POADBEntities context, Title title)
        {
            _context = context;
            _title = title;
        }


        //
        // GET: /Title/
        [ChildActionOnly]
        public ActionResult All()
        {

            var models = _context.Titles
                  .Project().To<TitleSummaryViewModel>();

            return PartialView(models.ToArray());
        }

        //[Log("Viewed title {id}")]
        public ActionResult View(int id)
        {
            var model = _context.Titles
                .SingleOrDefault(i => i.Title_ID == id);

            if (model == null)
            {
                return RedirectToAction<HomeController>(c => c.Index())
                        .WithError("Unable to find the Title.  Maybe it was deleted?");

            }

            return View(new TitleDetailsViewModel
            {
                Title_ID = model.Title_ID,
                Title_Name = model.Title_Name,
                Title_Description = model.Title_Description
            });
        }

        public ActionResult New()
        {
            var form = new NewTitleForm
            {
                //AvailableUsers = GetAvailableUsers(),
                //AvailableIssueTypes = GetAvailableIssueTypes()
            };
            return View(form);
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken, Log("Created title")]
        public ActionResult New(NewTitleForm form)
        {
            if (!ModelState.IsValid)
            {
                return View(form);
            }


            _title.Title_Name = form.Title_Name;
            _title.Title_Description = form.Title_Description;
            _context.Titles.Add(_title);
            _context.SaveChanges();

            //return RedirectToAction("Index", "Home");
            return RedirectToAction<TitleController>(c => c.Index()).WithSuccess("Title created!");
        }

        [Log("Started to edit title {id}")]
        public ActionResult Edit(int id)
        {
            var title = _context.Titles
                .Project().To<EditTitleForm>()
                .SingleOrDefault(i => i.Title_ID == id);

            if (title == null)
            {
                return RedirectToAction<TitleController>(c => c.Index())
                        .WithError("Unable to find the Title.  Maybe it was deleted?");
            }

            return View(title);
        }

        [HttpPost, Log("Saving changes")]
        public ActionResult Edit(EditTitleForm form)
        {
            if (!ModelState.IsValid)
            {
                return View(form);
            }

            var title = _context.Titles.SingleOrDefault(i => i.Title_ID == form.Title_ID);

            if (title == null)
            {
                return RedirectToAction<TitleController>(c => c.Index())
                        .WithError("Unable to find the Title.  Maybe it was deleted?");
            }


            title.Title_Name = form.Title_Name;
            title.Title_Description = form.Title_Description;
            _context.SaveChanges();

            return this.RedirectToAction(c => c.View(form.Title_ID))
                  .WithSuccess("Changes saved!");

        }

        [HttpPost, ValidateAntiForgeryToken, Log("Deleted title {id}")]
        public ActionResult Delete(int id)
        {
            var title = _context.Titles.Find(id);

            if (title == null)
            {
                return this.RedirectToAction<TitleController>(c => c.Index())
                       .WithError("Unable to find the Title.  Maybe it was deleted?");
            }

            _context.Titles.Remove(title);

            _context.SaveChanges();

            return RedirectToAction<TitleController>(c => c.Index()).WithSuccess("Title deleted!");
        }

        public ActionResult Cancel()
        {
            return RedirectToAction<TitleController>(c => c.Index());
        }

    }
}

POA.Web/Views/Title/All.cshtml
@model POA.Web.Models.Title.TitleSummaryViewModel[]
<br />
<br />
<div>
    @Html.ActionLink("Create New Title", "New", "Title", new { @class = "btn btn-primary" })
</div>
<table class="table table-hover">
   
    <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>            
        </tr>
    </thead>
    <tbody class="row-link" data-link="row">
        @foreach (var title in Model)
        {
            <tr>
                <td>@Html.ActionLink(@title.Title_Name, "View", "Title", routeValues: new { id = @title.Title_ID }, htmlAttributes: null)</td>
                <td>@title.Title_Description</td>

            </tr>
        }
    </tbody>
</table>

POA.Web/Views/Title/Edit.cshtml
@model POA.Web.Models.Title.EditTitleForm
@{
    ViewBag.Title = "Edit " + Model.Title_Name;
}

<h2>Edit Title</h2>
@using (Html.BeginForm("Edit", "Title", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.HiddenFor(m => m.Title_ID)
   
     @Html.EditorForModel()
        
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save Changes" class="btn btn-primary" />
            @Html.ActionLink("Cancel", "Cancel", "Title", new { @class = "btn btn-primary" })
        </div>
    </div>
}

POA.Web/Views/Title/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Action("All", "Title")

POA.Web/Views/Title/New.cshtml
@model POA.Web.Models.Title.NewTitleForm

@{
    ViewBag.Title = "New Title";
}

<h2>New Issue</h2>
@using (Html.BeginForm("New", "Title", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
     @Html.EditorForModel()
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Add Title" class="btn btn-primary" />
            @Html.ActionLink("Cancel", "Cancel", "Title", new { @class = "btn btn-primary" })
        </div>
    </div>
}

POA.Web/Views/Title/View.cshtml
@model POA.Web.Models.Title.TitleDetailsViewModel

@{
    ViewBag.Title = Model.Title_Name;
}

<h2>
    @*<img src="~/Content/IssueTypes/@(Model.IssueType).png" /> @Model.Subject
        <small class="pull-right">Received @Model.CreatedAt from @Model.CreatorUserName</small>*@
</h2>

<div class="well">
    <p class="lead">
        @Model.Title_Name
    </p>

    <p class="lead">
        @Model.Title_Description
    </p>
</div>
<div>
    @using (Html.BeginForm("Delete", "Title", new { id = Model.Title_ID }, FormMethod.Post, new { id = "delete-form" }))
    {
        @Html.AntiForgeryToken()
        @Html.ActionLink("Edit Title", "Edit", "Title", new { id = Model.Title_ID }, new { @class = "btn btn-primary" })
        <button type="submit" class="btn btn-warning">Delete Title</button>
        @Html.ActionLink("Cancel", "Cancel", "Title", new { @class = "btn btn-primary" })
    }

</div>



@section scripts
{
    <script>
        $(function () {
            $("#delete-form").on("submit", function () {
                return confirm("Are you sure you wish to delete this title?  You cannot undo this action.");
            });
        });
    </script>
}