POA.Web/Models/Agent/AgentDetails.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace POA.Web.Models.Agent
{
    public class AgentDetails
    {
        public int Agent_ID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Middle_Name { get; set; }
        public string City { get; set; }
        public string KifleKetema { get; set; }
        public string Wereda { get; set; }
        public string House_No { get; set; }
        public string ID_No { get; set; }
        public string BirthName { get; set; }
        public string CitizenName { get; set; }
        public string ResidenceName { get; set; }
        public string TitleName { get; set; }
        public string Email { get; set; }
        public string Phone_No { get; set; }
    }
}

POA.Web/Models/Agent/AgentDetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace POA.Web.Models.Agent
{
    public class AgentDetailsViewModel
    {
        public int Agent_ID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Middle_Name { get; set; }
        public string City { get; set; }
        public string KifleKetema { get; set; }
        public string Wereda { get; set; }
        public string House_No { get; set; }
        public string ID_No { get; set; }
        public int Country_Of_Birth_ID { get; set; }
        public int Country_Of_CitizenShip_ID { get; set; }
        public int Country_Of_Residence_ID { get; set; }
        public int Title_ID { get; set; }
        public string Email { get; set; }
        public string Phone_No { get; set; }
    }
}

POA.Web/Models/Agent/AgentSummaryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using POA.Web.Infrastructure.Mapping;

namespace POA.Web.Models.Agent
{
    public class AgentSummaryViewModel : IMapFrom<Domain.Agent>
    {
        public int Agent_ID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Middle_Name { get; set; }
        public string City { get; set; }
        public string KifleKetema { get; set; }
        public string Wereda { get; set; }
        public string House_No { get; set; }
        public string ID_No { get; set; }
        public int Country_Of_Birth_ID { get; set; }
        public int Country_Of_CitizenShip_ID { get; set; }
        public int Country_Of_Residence_ID { get; set; }
        public int Title_ID { get; set; }
        public string Email { get; set; }
        public string Phone_No { get; set; }
    }
}

POA.Web/Models/Agent/EditAgentForm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using POA.Web.Infrastructure.Mapping;

namespace POA.Web.Models.Agent
{
    public class EditAgentForm : IMapFrom<Domain.Agent>
    {
        [DisplayName("Title")]
        public string Title_ID { get; set; }

        [HiddenInput]
        public int Agent_ID { get; set; }

        [Required, DisplayName("First Name")]
        public string First_Name { get; set; }

        [Required, DisplayName("Last Name")]
        public string Last_Name { get; set; }

        [Required, DisplayName("Middle Name")]
        public string Middle_Name { get; set; }

        [Required]
        public string City { get; set; }

        [Required]
        public string KifleKetema { get; set; }

        [Required]
        public string Wereda { get; set; }

        [Required, DisplayName("House No.")]
        public string House_No { get; set; }

        [Required, DisplayName("ID No.")]
        public string ID_No { get; set; }

        [DisplayName("Country Of Birth")]
        public string Country_Of_Birth_ID { get; set; }

        [DisplayName("Country Of CitizenShip")]
        public string Country_Of_CitizenShip_ID { get; set; }

        [DisplayName("Country Of Residence")]
        public string Country_Of_Residence_ID { get; set; }


        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [DisplayName("Phone")]
        public string Phone_No { get; set; }
    }
}

POA.Web/Models/Agent/NewAgentForm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using POA.Web.Infrastructure.Mapping;

namespace POA.Web.Models.Agent
{
    public class NewAgentForm : IMapFrom<Domain.Agent>
    {
        [DisplayName("Title")]
        public String Title_ID { get; set; }

        [HiddenInput]
        public int Agent_ID { get; set; }

        [Required, DisplayName("First Name")]
        public string First_Name { get; set; }

        [Required, DisplayName("Last Name")]
        public string Last_Name { get; set; }

        [Required, DisplayName("Middle Name")]
        public string Middle_Name { get; set; }

        [Required]
        public string City { get; set; }

        [Required]
        public string KifleKetema { get; set; }

        [Required]
        public string Wereda { get; set; }

        [Required, DisplayName("House No.")]
        public string House_No { get; set; }

        [Required, DisplayName("ID No.")]
        public string ID_No { get; set; }

        [DisplayName("Country Of Birth")]
        public string Country_Of_Birth_ID { get; set; }

        [DisplayName("Country Of CitizenShip")]
        public string Country_Of_CitizenShip_ID { get; set; }

        [DisplayName("Country Of Residence")]
        public string Country_Of_Residence_ID { get; set; }
        

        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [DisplayName("Phone")]
        public string Phone_No { get; set; }

        
    }
}

POA.Web/Models/PowerOfAttorney/AgentModel.cs
using POA.Web.Infrastructure.Mapping;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace POA.Web.Models.PowerOfAttorney
{
    public class AgentModel : IMapFrom<Domain.Agent>
    {

        [DisplayName("Agent")]
        public String Agent_ID { get; set; }  
    }
}

POA.Web/Models/PowerOfAttorney/CategoryModel.cs
using POA.Web.Infrastructure.Mapping;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace POA.Web.Models.PowerOfAttorney
{
    public class CategoryModel : IMapFrom<Domain.Category>
    {
        [HiddenInput]
        public int Category_ID { get; set; }

        [DisplayName(" ")]
        public string POASub_Categories { get; set; }    
    }
}

POA.Web/Models/PowerOfAttorney/PrincipalModel.cs
using POA.Web.Infrastructure.Mapping;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace POA.Web.Models.PowerOfAttorney
{
    public class PrincipalModel: IMapFrom<Domain.Agent>
    {

        [DisplayName("Principal")]
        public String Principal_ID { get; set; }  
    }
   
}

POA.Web/Models/PowerOfAttorney/SubCategoryModel.cs
using POA.Domain;
using System;
using System.Collections.Generic;
using System.Data.Entity.SqlServer;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace POA.Web.Models.PowerOfAttorney
{
    public class SubCategoryModel
    {
        private readonly POADBEntities _context;
        // This property contains the available options
        public SelectList SubCategorySources { get; set; }

        // This property contains the selected options
        public IEnumerable<string> SelectedSources { get; set; }

        public SubCategoryModel(POADBEntities context, string strCategoryID)
        {
            _context = context;
            strCategoryID = !string.IsNullOrEmpty(strCategoryID) ? strCategoryID : "2";

           var availableSubCategories = from cs in _context.Category_SubCategory
                                  join sc in _context.SubCategories on cs.SubCategory_ID equals sc.SubCategory_ID
                                  where SqlFunctions.StringConvert((double)cs.Category_ID).Trim() == strCategoryID
                                  select new
                                  {
                                      Text = sc.Name,
                                      Value = SqlFunctions.StringConvert((double)cs.SubCategory_ID).Trim()
                                  };
            

            SubCategorySources = new SelectList(availableSubCategories.ToArray(), "Value", "Text");            

        }
    }
}

POA.Web/Controllers/AgentController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using POA.Domain;
using POA.Web.Filters;
using POA.Web.Models;
using POA.Web.Models.Title;
using Microsoft.Web.Mvc;
using POA.Web.Infrastructure.Alerts;
using AutoMapper.QueryableExtensions;
using POA.Web.Models.Agent;

namespace POA.Web.Controllers
{
	public class AgentController : BaseController
	{
		// GET: Agent
		public ActionResult Index()
		{
			return View();
		}

		private readonly  POADBEntities _context;
	   private Agent _agent { get; set; }

	   public AgentController(POADBEntities context, Agent agent)
	  {
		  _context = context;
		  _agent = agent;
	  }
			

		//
		// GET: /agent/
	  [ChildActionOnly]
	  public ActionResult All()
	  {

		  var models = _context.Agents
				.Project().To<AgentSummaryViewModel>();          

		  return PartialView(models.ToArray()); 
	  }

	 // [Log("Viewed agent {id}")]
	  public ActionResult View(int id)
	  {
		  var model = _context.Agents
			  .SingleOrDefault(i => i.Agent_ID == id);

		  if (model == null)
		  {
			  return RedirectToAction<AgentController>(c => c.Index())
					  .WithError("Unable to find the user.  Maybe it was deleted?");
			  
		  }

		  return View(new AgentDetailsViewModel
			  {
				  Agent_ID = model.Agent_ID,
				  First_Name = model.First_Name,
				  Last_Name = model.Last_Name
			  });
	  }

	  public ActionResult GetUserByID(int id)
	  {
		  //var model = _context.Agents              
		  //    .SingleOrDefault(i => i.Agent_ID == id);

		  AgentDetails model = (from a in _context.Agents
					  join cob in _context.Countries
					  on a.Country_Of_Birth_ID equals cob.Country_ID
					  join cor in _context.Countries
					  on a.Country_Of_Residence_ID equals cor.Country_ID
					  join coc in _context.Countries
					  on a.Country_Of_CitizenShip_ID equals coc.Country_ID
					  join t in _context.Titles
					  on a.Title_ID equals t.Title_ID
					  where a.Agent_ID == id
					  select new AgentDetails
					  {
						  Agent_ID = a.Agent_ID,
						  First_Name = a.First_Name,
						  Last_Name = a.Last_Name,
						  City = a.City,
						  Middle_Name = a.Middle_Name,
						  Phone_No = a.Phone_No,
						  KifleKetema = a.KifleKetema,
						  ID_No = a.ID_No,
						  House_No = a.House_No,
						  Email = a.Email,
						  BirthName = cob.Name,
						  CitizenName = coc.Name,
						  ResidenceName = cor.Name,
						  TitleName = t.Title_Name
					  }).SingleOrDefault();



		  if (model == null)
		  {
			  return RedirectToAction<AgentController>(c => c.Index())
					  .WithError("Unable to find the user.  Maybe it was deleted?");

		  }

		 // AgentDetails objAgentDetail = (AgentDetails)(model);
		  

		  return Json(model, JsonRequestBehavior.AllowGet);
	  }

		

	  public ActionResult New()
	  {
		  var form = new NewAgentForm
		  {
			  
		  };
		  return View(form);
	  }

	  [HttpPost, ValidateAntiForgeryToken, Log("Created agent")]
	  public ActionResult New(NewAgentForm form)
	  {
		  if (!ModelState.IsValid)
		  {             
			  return View(form);
		  }

		  //var cobID = _context.Countries.Single(u => u.Country_ID == form.Country_Of_Birth_ID.Country_ID);
		  int intCobID = Convert.ToInt32(form.Country_Of_Birth_ID);
		  int intCorID = Convert.ToInt32(form.Country_Of_Residence_ID);
		  int intCocID = Convert.ToInt32(form.Country_Of_CitizenShip_ID);
		  int inttitleID = Convert.ToInt32(form.Title_ID);
		  var cobID = _context.Countries.Single(u => u.Country_ID == intCobID);
		  var corID = _context.Countries.Single(u => u.Country_ID == intCorID);
		  var cocID = _context.Countries.Single(u => u.Country_ID == intCocID );
		  var titleID = _context.Titles.Single(u => u.Title_ID == inttitleID);
		  _agent.First_Name = form.First_Name;
		  _agent.Last_Name = form.Last_Name;
		  _agent.Middle_Name = form.Middle_Name;
		  _agent.City = form.City;
		  _agent.Email = form.Email;
		  _agent.House_No = form.House_No;
		  _agent.ID_No = form.ID_No;
		  _agent.KifleKetema = form.KifleKetema;
		  _agent.Wereda = form.Wereda;
		  _agent.Phone_No = form.Phone_No;
		  _agent.Title_ID = titleID.Title_ID;
		  _agent.Country_Of_Birth_ID = cobID.Country_ID;
		  _agent.Country_Of_CitizenShip_ID = cocID.Country_ID;
		  _agent.Country_Of_Residence_ID = corID.Country_ID;
		  _context.Agents.Add(_agent);
		  _context.SaveChanges();

		  //return RedirectToAction("Index", "Home");
		  return RedirectToAction<AgentController>(c => c.Index()).WithSuccess("user created!"); 
	  }

	  [Log("Started to edit user {id}")]
	  public ActionResult Edit(int id)
	  {
		  var agent = _context.Agents
			  .Project().To<EditAgentForm>()
			  .SingleOrDefault(i => i.Agent_ID == id);       

		  if (agent == null)
		  {
			  return RedirectToAction<AgentController>(c => c.Index())
					  .WithError("Unable to find the user.  Maybe it was deleted?");
		  }

		  return View(agent);
	  }

	  [HttpPost, Log("Saving changes")]
	  public ActionResult Edit(EditAgentForm form)
	  {
		  if (!ModelState.IsValid)
		  {
			return View(form);
		  }

		  var _agent = _context.Agents.SingleOrDefault(i => i.Agent_ID == form.Agent_ID);

		  if (_agent == null)
		  {
			  return RedirectToAction<AgentController>(c => c.Index())
					  .WithError("Unable to find the agent.  Maybe it was deleted?");
		  }


		  int intCobID = Convert.ToInt32(form.Country_Of_Birth_ID);
		  int intCorID = Convert.ToInt32(form.Country_Of_Residence_ID);
		  int intCocID = Convert.ToInt32(form.Country_Of_CitizenShip_ID);
		  int inttitleID = Convert.ToInt32(form.Title_ID);
		  var cobID = _context.Countries.Single(u => u.Country_ID == intCobID);
		  var corID = _context.Countries.Single(u => u.Country_ID == intCorID);
		  var cocID = _context.Countries.Single(u => u.Country_ID == intCocID);
		  var titleID = _context.Titles.Single(u => u.Title_ID == inttitleID);
		  _agent.First_Name = form.First_Name;
		  _agent.Last_Name = form.Last_Name;
		  _agent.Middle_Name = form.Middle_Name;
		  _agent.City = form.City;
		  _agent.Email = form.Email;
		  _agent.House_No = form.House_No;
		  _agent.ID_No = form.ID_No;
		  _agent.KifleKetema = form.KifleKetema;
		  _agent.Wereda = form.Wereda;
		  _agent.Phone_No = form.Phone_No;
		  _agent.Title_ID = titleID.Title_ID;
		  _agent.Country_Of_Birth_ID = cobID.Country_ID;
		  _agent.Country_Of_CitizenShip_ID = cocID.Country_ID;
		  _agent.Country_Of_Residence_ID = corID.Country_ID;         
		  _context.SaveChanges();

		  return this.RedirectToAction(c => c.View(form.Agent_ID))
				.WithSuccess("Changes saved!");
		  
	  }

	  [HttpPost, ValidateAntiForgeryToken, Log("Deleted user {id}")]
	  public ActionResult Delete(int id)
	  {
		  var agent = _context.Agents.Find(id);

		  if (agent == null)
		  {
			  return this.RedirectToAction<AgentController>(c => c.Index())
					 .WithError("Unable to find the user.  Maybe it was deleted?");
		  }

		  _context.Agents.Remove(agent);

		  _context.SaveChanges();

		  return RedirectToAction<AgentController>(c => c.Index()).WithSuccess("user deleted!"); 
	  }

		public ActionResult Cancel()
	  {
		  return RedirectToAction<AgentController>(c => c.Index());
	  }
	}
}

POA.Web/Controllers/PowerOfAttorneyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace POA.Web.Controllers
{
    public class PowerOfAttorneyController : BaseController
    {
        // GET: PowerOfAttorney
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult New()
        {            
            return View();
        }
    }
}

POA.Web/Views/PowerOfAttorney/AgentForm.cshtml
@model POA.Web.Models.PowerOfAttorney.AgentModel

@{
    ViewBag.Title = "Agent";
}


  
    @Html.EditorForModel()

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">           
        </div>
    </div>

POA.Web/Views/PowerOfAttorney/CatSubCatForm.cshtml
@model POA.Web.Models.PowerOfAttorney.CategoryModel

@{
    ViewBag.Title = "Category";
}


@Html.EditorForModel()

<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
    </div>
</div>

POA.Web/Views/PowerOfAttorney/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

@Html.Action("New", "PowerOfAttorney")

POA.Web/Views/PowerOfAttorney/New.cshtml
@using System;
@using System.Collections.Generic;
@using System.Linq;
@using System.Web;
@using System.Web.Mvc;
@using System.Web.Optimization;
@using StructureMap.TypeRules;
@using POA.Web.Infrastructure.Tasks;
@using POA.Domain
@using POA.Web.Infrastructure
@using System.Data.Entity.SqlServer
@using StructureMap
@using System.Collections

<script src="~/Scripts/angular.js"></script>
@using (Html.BeginForm("New", "PowerOfAttorney", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    <div ng-app="poaApp">
        <div ng-controller="AppCtrl">
           
            @Html.Partial("PrincipalForm")<button ng-click="show()">Show</button>
            @Html.Partial("AgentForm")

           @using (POADBEntities _context = new POADBEntities())
            {
            var availableCategories = _context.Categories.Select(u => new SelectListItem
            {
            Text = u.Name,
            Value = SqlFunctions.StringConvert((double)u.Category_ID).Trim()

            }).ToArray();

            //availableCategories.Select(x => x.Value).ToList();

            foreach (SelectListItem sli in availableCategories)
            {

                <div id="show-section_@sli.Value" ng-click="section_(@sli.Value)" ng-class="{'btn-primary': is(@sli.Value)}" style="margin-left:120px;font-weight:bold;"> @sli.Text</div>
                @*<p ng-click="section_(@sli.Value)" ng-class="{'btn-primary': is(@sli.Value)}"> @sli.Text</p>*@
                <div id="section_@sli.Value" ng-show="is(@sli.Value)">
                    @Html.Partial("CatSubCatForm", new ViewDataDictionary { { "id", sli.Value } })

                </div>

            }

            }

            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add Power Of Attorney" class="btn btn-primary" />
                @Html.ActionLink("Cancel", "Cancel", "PowerOfAttorney", new { @class = "btn btn-primary" })
            </div>

        </div>
    </div>
}



<script src="~/Scripts/app/poaApp.js"></script>
<script src="~/Scripts/app/controllers/AppCtrl.js"></script>

POA.Web/Views/PowerOfAttorney/PrincipalForm.cshtml
@model POA.Web.Models.PowerOfAttorney.PrincipalModel

@{
    ViewBag.Title = "Principal";
}



@Html.EditorForModel()

<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
    </div>
</div>


<div style="width:50%; padding-left:150px;">
    <table>
        <tr>
            <td><b>Title:</b>&nbsp;</td>
            <td>{{item.TitleName}}</td>
        </tr>
        <tr>
            <td><b>First Name:</b>&nbsp;</td>
            <td>{{item.First_Name}}</td>
        </tr>
        <tr>
            <td><b>Middle Name:</b>&nbsp;</td>
            <td>{{item.Middle_Name}}</td>
        </tr>
        <tr>
            <td><b>Last Name:</b>&nbsp;</td>
            <td>{{item.Last_Name}}</td>
        </tr>
        <tr>
            <td><b>City:</b>&nbsp;</td>
            <td>{{item.City}}</td>
        </tr>
        <tr>
            <td><b>Kifle Ketema:</b> &nbsp;</td>
            <td>{{item.KifleKetema}}</td>
        </tr>
        <tr>
            <td><b>House No:</b>&nbsp;</td>
            <td>{{item.House_No}}</td>
        </tr>
        <tr>
            <td><b>ID No.:</b>&nbsp;</td>
            <td>{{item.ID_No}}</td>
        </tr>
        <tr>
            <td><b>Country Of Birth:</b>&nbsp;</td>
            <td>{{item.BirthName}}</td>
        </tr>
        <tr>
            <td><b>Country Of Citizenship:</b>&nbsp;</td>
            <td>{{item.CitizenName}}</td>
        </tr>
        <tr>
            <td><b>Country Of Residence:</b>&nbsp;</td>
            <td>{{item.ResidenceName}}</td>
        </tr>
        <tr>
            <td><b>Email Address:</b>&nbsp;</td>
            <td>{{item.Email}}</td>
        </tr>
        <tr>
            <td><b>Phone No.:</b>&nbsp;</td>
            <td>{{item.Phone_No}}</td>
        </tr>
    </table>
        
   
</div>